apiVersion: apps/v1
kind: Deployment
metadata:
 name: testclient
 labels:
   app: testclient
spec:
 selector:
  matchLabels:
   app: testclient
 template:
  metadata:
   labels:
    app: testclient
  spec:
   containers:
   - image: ip_address_of_the_machine:5000/nodejs-api-image:latest
     name: nodejs-api
     imagePullPolicy: Always
     ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: testclient-svc
spec:
    ports:
    - name: “testclient”
      targetPort: 3000
      port: 3000
      nodePort: 30253
      protocol: TCP
    selector:
       app: testclient
    type: NodePort
